//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractFactoryEmployeeDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string JobDescription { get; set; }
        public string Department { get; set; }
        public string ComputerDetails { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
